import { NextRequest, NextResponse } from "next/server";
import { writeFileSync, existsSync, mkdirSync, unlinkSync, readdirSync } from "fs";
import { join } from "path";
import { findEdgeTXMountPoint } from "@/lib/usb-detector";
import { analyzeSDCard, backupSDCard } from "@/lib/radio-analyzer";
import {
  RADIOS,
  DRONES,
  ELRS_BEGINNER_CONFIG,
  generateEdgeTXModel,
} from "@/lib/config-templates";
import { generateSimModel } from "@/lib/simulator-templates";

export const dynamic = "force-dynamic";

/**
 * GET /api/analyze — Full SD card analysis
 */
export async function GET() {
  const mountPoint = findEdgeTXMountPoint();

  if (!mountPoint) {
    return NextResponse.json({
      success: false,
      error: "Aucune carte SD EdgeTX détectée.",
      hint: "Branche ta radio en USB et choisis 'USB Storage' sur l'écran de la radio.",
      steps: [
        "Branche le câble USB-C entre ta radio et ton Mac",
        "Sur l'écran de la radio, choisis 'USB Storage' (pas Joystick, pas Serial)",
        "Attends que le Mac monte le volume",
        "Relance le scan dans le dashboard",
      ],
    });
  }

  const analysis = analyzeSDCard(mountPoint);

  return NextResponse.json({
    success: true,
    analysis,
  });
}

/**
 * POST /api/analyze — Execute actions on the SD card
 *
 * Actions:
 * - backup: Backup current SD card contents
 * - clean-inject: Backup, remove old models, inject fresh configs
 * - inject-all: Inject all 4 drone configs + 1 sim model (keeps existing)
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const action = body.action as string;
    const bindingPhrase = (body.bindingPhrase as string) || "";

    const mountPoint = findEdgeTXMountPoint();
    if (!mountPoint) {
      return NextResponse.json(
        { success: false, error: "Carte SD non détectée" },
        { status: 404 }
      );
    }

    // ---- BACKUP ----
    if (action === "backup") {
      const result = backupSDCard(mountPoint);
      return NextResponse.json({ success: result.success, backup: result });
    }

    // ---- INJECT ALL (keep existing) ----
    if (action === "inject-all") {
      const backup = backupSDCard(mountPoint);
      if (!backup.success) {
        return NextResponse.json({
          success: false,
          error: `Backup échoué: ${backup.message}`,
        });
      }

      const modelsDir = join(mountPoint, "MODELS");
      if (!existsSync(modelsDir)) {
        mkdirSync(modelsDir, { recursive: true });
      }

      const elrs = { ...ELRS_BEGINNER_CONFIG, bindingPhrase };
      let injected = 0;

      // Inject all 4 drone combos
      for (const radio of Object.values(RADIOS)) {
        for (const drone of Object.values(DRONES)) {
          const template = generateEdgeTXModel(radio, drone, elrs);
          writeFileSync(join(modelsDir, template.filename), template.content, "utf-8");
          injected++;
        }
      }

      // Inject sim models
      for (const radioId of ["tx16s", "pocket"] as const) {
        const simModel = generateSimModel(radioId);
        writeFileSync(join(modelsDir, simModel.filename), simModel.content, "utf-8");
        injected++;
      }

      return NextResponse.json({
        success: true,
        message: `${injected} modèles injectés sur la carte SD (backup effectué)`,
        backup,
        injected,
        files: [
          "hulk2_tx16s.yml", "hulk2_pocket.yml",
          "nazgul_tx16s.yml", "nazgul_pocket.yml",
          "simu_tx16s.yml", "simu_pocket.yml",
        ],
      });
    }

    // ---- CLEAN + INJECT (remove old, inject fresh) ----
    if (action === "clean-inject") {
      // 1. Backup first
      const backup = backupSDCard(mountPoint);
      if (!backup.success) {
        return NextResponse.json({
          success: false,
          error: `Backup échoué: ${backup.message}. Opération annulée.`,
        });
      }

      const modelsDir = join(mountPoint, "MODELS");

      // 2. Remove old yml models generated by us (keep user's own models)
      let removed = 0;
      if (existsSync(modelsDir)) {
        const generatedPatterns = [
          "hulk2_tx16s.yml", "hulk2_pocket.yml",
          "nazgul_tx16s.yml", "nazgul_pocket.yml",
          "simu_tx16s.yml", "simu_pocket.yml",
        ];
        for (const f of readdirSync(modelsDir)) {
          if (generatedPatterns.includes(f)) {
            try {
              unlinkSync(join(modelsDir, f));
              removed++;
            } catch { /* ignore */ }
          }
        }
      } else {
        mkdirSync(modelsDir, { recursive: true });
      }

      // 3. Inject fresh configs
      const elrs = { ...ELRS_BEGINNER_CONFIG, bindingPhrase };
      let injected = 0;

      for (const radio of Object.values(RADIOS)) {
        for (const drone of Object.values(DRONES)) {
          const template = generateEdgeTXModel(radio, drone, elrs);
          writeFileSync(join(modelsDir, template.filename), template.content, "utf-8");
          injected++;
        }
      }

      for (const radioId of ["tx16s", "pocket"] as const) {
        const simModel = generateSimModel(radioId);
        writeFileSync(join(modelsDir, simModel.filename), simModel.content, "utf-8");
        injected++;
      }

      return NextResponse.json({
        success: true,
        message: `Clean & inject terminé: ${removed} anciens supprimés, ${injected} nouveaux injectés`,
        backup,
        removed,
        injected,
      });
    }

    return NextResponse.json(
      { success: false, error: `Action inconnue: ${action}` },
      { status: 400 }
    );
  } catch (error) {
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 }
    );
  }
}
